<?php

// This file was generated by running "composer dump-env test"

return array (
  'APP_ENV' => 'test',
  'APP_SECRET' => '$ecretf0rt3st',
  'DATABASE_URL' => 'mysql://root:K@reemp455@127.0.0.1:3306/crud?serverVersion=10.4.18',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem-back',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '123456',
  'KERNEL_CLASS' => 'App\\Kernel',
  'SYMFONY_DEPRECATIONS_HELPER' => '999999',
  'PANTHER_APP_ENV' => 'panther',
  'PANTHER_ERROR_SCREENSHOT_DIR' => './var/error-screenshots',
);
